version: '3.8'

services:
  web:
    build: ./DjangoOnDocker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app://usr/src/DjangoOnDocker
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
